gerenciador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from project import views

urlpatterns = [
    path('criar_projeto/', views.criar_projeto, name='criar_projeto'),
    # URL para criar um novo projeto.
    
    path('', views.inicial, name='projetos'),
    # URL para a página inicial que mostra todos os projetos em andamento.

    path('adicionar_funcao/<int:projeto_id>/', views.adicionar_funcao, name='nova_funcao'),
    # URL para adicionar uma nova função básica a um projeto específico.

    path('detalhes_projeto/<int:projeto_id>/', views.detahes_projeto, name='detalhes_projeto'),
    # URL para exibir os detalhes de um projeto específico.

    path('adicionar_trabalho/<int:projeto_id>/', views.adicionar_diasTrabalho, name='adicionar_trabalho'),
    # URL para adicionar um registro de horas de trabalho a um projeto específico.

    path('marcar_concluida/<int:projeto_id>/', views.conclui_funcao, name='marcar_concluida'),
    # URL para marcar uma função básica como concluída em um projeto específico.

    path('detalhes_funcao/<int:projeto_id>/', views.detahes_funcao, name='detalhes_funcao'),
    # URL para exibir os detalhes de uma função básica em um projeto específico.

    path('update/funcao/<int:projeto_id>/', views.update_funcao, name='update_funcao'),
    # URL para atualizar os detalhes de uma função básica em um projeto específico.

    path('uptade/projeto/<int:projeto_id>/', views.update_projeto, name='update_projeto'),
    # URL para atualizar os detalhes de um projeto específico.

    path('todas_funcoes/<int:projeto_id>/', views.todas_funcoes, name='funcoes'),
    # URL para exibir todas as funcionalidades de um projeto específico.

    path('projetos/', views.todos_projetos, name='todos_projetos'),
    # URL para exibir todos os projetos cadastrados.

    path('apagar/projeto/<int:projeto_id>/', views.apagar_projeto, name='apagar_projeto'),
    # URL para apagar um projeto específico.

    path('apagar/funcao/<int:projeto_id>/', views.apagar_funcao, name='apagar_funcao'),
    # URL para apagar uma funcionalidade específica.

    path('pesquisar/', views.pesquisar, name='pesquisar'),
    # URL para realizar uma pesquisa nos projetos cadastrados.
]

project/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

    
class FuncionalidadesBasicas(models.Model):
    """
    Modelo para armazenar funções básicas de um projeto.
    
    Atributos:
        nome (str): O nome da função básica.
        descricao (str): Descrição da função básica.
        concluida (bool): Indica se a função básica foi concluída.
    """
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    concluida = models.BooleanField(default=False)
    
    def __str__(self):
        return self.nome
    
    
    def funcao_concluida(self):
        """
        Marca a função básica como concluída.
        """
        self.concluida = True
        self.save()
    
    
    
class EscolhasDificuldades:
    """
    Classe auxiliar para definir as escolhas de dificuldade do projeto.
    """
    DIFICULDADE_CHOICES = [
        ('simples', 'Simples'),
        ('intermediario', 'Intermediario'),
        ('complexo', 'Complexo'),
        ('falta de recursos', 'Falta de recursos'),
        ('prazos apertados', 'Prazos apertados'),
        ('falta de experiencia', 'Falta de experiência'),
        ('complexidade do projeto', 'Complexidade do projeto'),
        ('falta de comunicacao', 'Falta de comunicação'),
        ('falta de suporte da equipe', 'Falta de suporte da equipe'),
        ('mundancas constantes de requisitos', 'Mundanças constantes de requisitos'),
        ('conflitos de interesse', 'Conflitos de interesse'),
        ('problema de integracao', 'Problemas de integração'),
        ('outros', 'Outros'),
    ]


class EstadoProjeto:
    """
    Classe auxiliar para definir as escolhas de dificuldade do projeto.
    """
    ESTADOS_PROJETOS = (
        ('andamento', 'Em andamento'),
        ('pausado', 'Pausado'),
        ('finalizado', 'Finalizado'),
    )


class Prioridade:
    """
    Classe auxiliar para definir as escolhas de dificuldade do projeto.
    """
    PRIORIDADE_CHOICES = [
        ('baixa', 'Baixa'),
        ('media', 'Media'),
        ('alta', 'Alta'),
    ]



class Projeto(models.Model):
    """
    Modelo para representar um projeto.

    Atributos:
        nome (str): Nome do projeto.
        descricao (str): Descrição do projeto.
        funcoes_basicas (ManyToManyField): Funções básicas associadas ao projeto.
        dificuldade (str): Nível de dificuldade do projeto.
        prioridade (str): Prioridade do projeto.
        total_horas_gastas (float): Total de horas gastas no projeto.
        horas_previstas_por_dia (float): Horas previstas de trabalho por dia.
        email_usuario (str): Email do usuário responsável pelo projeto.
        dia_trabalho (ManyToManyField): Dias de trabalho associados ao projeto.
        estado_projeto (str): Estado atual do projeto.
        data_criada (DateTimeField): Data de criação do projeto.
        data_inicio (DateTimeField): Data de início do projeto.
        data_termino (DateTimeField): Data de término do projeto.
    """
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    funcoes_basicas = models.ManyToManyField('FuncionalidadesBasicas')
    dificuldade = models.CharField(max_length=50, choices=EscolhasDificuldades.DIFICULDADE_CHOICES)
    prioridade = models.CharField(max_length=10, choices=Prioridade.PRIORIDADE_CHOICES)
    total_horas_gastas = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    horas_previstas_por_dia = models.DecimalField(max_digits=5, decimal_places=2)
    email_usuario = models.EmailField(null=True, blank=True)
    dia_trabalho = models.ManyToManyField('DiaTrabalho')
    estado_projeto = models.CharField(max_length=50, choices=EstadoProjeto.ESTADOS_PROJETOS)
    data_criada = models.DateTimeField(auto_now_add=True)
    data_inicio = models.DateTimeField(null=True, blank=True)
    data_termino = models.DateTimeField(null=True, blank=True)
    
    
    class Meta: 
        verbose_name = 'Projeto'
        verbose_name_plural = 'Projetos'
        ordering = ['-total_horas_gastas']
    
    def __str__(self):
        return self.nome
    
    
    @property
    def days_ago(self):
        current_date = timezone.now()
        difference = current_date - self.data_criada
        return difference.days

    
    @property
    def hours_minutes_ago(self):
        current_date = timezone.now()
        difference = current_date - self.data_criada
        minutes, _ = divmod(difference.seconds, 60)
        if difference.days >= 1:
            return f"{difference.days} dias"
        elif difference.seconds >= 3600:
            return f"{difference.seconds // 3600} horas"
        else:
            return f"{minutes} minutos"
    
    
    def get_nome(self):
        return self.nome
    
    
    def set_nome(self, nome):
        self.nome = nome
        self.save()
        

    def get_estado(self):

        return self.estado_projeto
    
    
    def get_email(self):
        return self.email_usuario


    def get_horas_previstas_por_dia(self):
        """
        Retorna o número de horas previstas por dia para o projeto.

        Returns:
            Decimal: O número de horas previstas por dia para o projeto.
        """
        return self.horas_previstas_por_dia
    
    
    def set_horas_previstas_por_dia(self, horas):
        
        """
        Define o número de horas previstas por dia para o projeto e salva no banco de dados.

        Args:
            horas (Decimal): O número de horas previstas por dia para o projeto.
        """
        
        self.horas_previstas_por_dia = horas
        self.save()

        
    def get_dificuldade(self):
        
        return self.dificuldade


    def horas_gastas(self, tempo_feito):

        self.total_horas_gastas += tempo_feito
        self.save()
    
    
    
class DiaTrabalho(models.Model):
    """
    Modelo para representar um dia de trabalho em um projeto.
    
    Atributos:
        data (date): Data do dia de trabalho.
        horas (float): Horas trabalhadas no dia.
        bateu_hora_prevista (bool): Indica se as horas trabalhadas bateram com as horas previstas.
        passou_hora_prevista (bool): Indica se as horas trabalhadas ultrapassaram as horas previstas (considerando de 1 hora para cima).
    """
    
    data = models.DateField(auto_now_add=True)
    horas = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    bateu_hora_prevista = models.BooleanField(default=False)
    passou_hora_prevista = models.BooleanField(default=False)

    def __str__(self):
        return str(self.data)
    
    
    def data_trabalho(self):
        """
        Retorna a data do dia de trabalho formatada como uma string.

        Returns:
            str: A data do dia de trabalho formatada como uma string.
        """
        return str(self.data)
    
    
    def get_horas_feitas(self):
        """
        Retorna as horas feitas no dia.
        
        Returns:
            float: Horas feitas no dia.
        """
        return self.horas

    
    
    def bateu_meta(self):
        """
        Marca que as horas trabalhadas bateram com as horas previstas.
        """
        self.bateu_hora_prevista = True
        self.save()
        

    def nao_bateu_meta(self):
        """
        Marca que as horas trabalhadas ultrapassaram as horas previstas.
        """
        self.bateu_hora_prevista = False
        self.save()


    def ja_passou_hora_prevista(self):
        """
        Marca que as horas trabalhadas ultrapassaram as horas previstas no dia e salva no banco de dados.

        Esse método deve ser chamado quando as horas trabalhadas ultrapassam as horas previstas no dia de trabalho.
        Ele define o atributo passou_hora_prevista como True e salva essa alteração no banco de dados.

        """

        self.passou_hora_prevista = True
        self.save()

project/forms.py
from django import forms
from .models import Projeto, FuncionalidadesBasicas, DiaTrabalho


class FormProjeto(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = ['nome', 'descricao', 'dificuldade', 'prioridade', 'estado_projeto', 'horas_previstas_por_dia']


class FuncaoForm(forms.ModelForm):
    class Meta:
        model = FuncionalidadesBasicas
        fields = ['nome', 'descricao']
        
        

class DiaTrabalhoForm(forms.ModelForm):
    class Meta:
        model = DiaTrabalho
        fields = ['horas']

project/templates/visualizar/detalhes_funcao.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
    }

    .bi {
        vertical-align: -.125em;
        fill: currentColor;
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
        z-index: 1500;
    }
</style>


<div class="col-lg-8 mx-auto p-4 py-md-5">
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
            <svg class="bi me-2" width="40" height="32">
                <use xlink:href="#bootstrap" />
            </svg>
            <span class="fs-4">Mais Detalhes</span> <!--Aqui vai aparecer o estado da função-->
        </a>
    </header>

    <main>
        <h1 class="text-body-emphasis">{{funcao.nome}}</h1>
        <p class="fs-5 col-md-8">{{funcao.descricao}}</p>

        <div class="mb-5">
            <a href="{% url 'update_funcao' projeto_id=funcao.id %}" class="btn btn-success btn-lg px-4">Editar</a>
            <button class="btn btn-danger" type="button"
                onclick="window.location.href='{% url 'apagar_funcao' projeto_id=funcao.id %}' ">Apagar</button>
        </div>

        <hr class="col-3 col-md-2 mb-5">

        <div class="col-lg-6 col-xxl-4 my-5 mx-auto">
            <div class="d-grid gap-2">
                <button class="btn btn-danger" type="button"
                    onclick="window.location.href='{% url 'marcar_concluida' projeto_id=funcao.id %}' ">Finalizar</button>

            </div>
        </div>

    </main>
</div>

{% endblock %}

project/templates/visualizar/detalhes_projeto.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
    }

    .bi {
        vertical-align: -.125em;
        fill: currentColor;
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
        z-index: 1500;
    }
</style>

<main>

    <div class="col-lg-8 mx-auto p-4 py-md-5">


        <main>
            <h1 class="text-body-emphasis">{{ projeto.nome }}</h1>
            <p class="fs-5 col-md-8">{{ projeto.descricao }}</p>

            <div class="mb-5">
                <a href="{% url 'update_projeto' projeto_id=projeto.id %}"
                    class="btn btn-success btn-lg px-4">Editar</a>

            </div>

            <hr class="col-3 col-md-2 mb-5">

            <div class="row g-5">
                <div class="col-md-6">
                    <h2 class="text-body-emphasis">Funcionalidades</h2>
                    <p>Ready to beyond the starter template? Check out these open source projects that you can quickly
                        duplicate to a new GitHub repository.</p>
                    <ul class="list-unstyled ps-0">
                        {% for funcao in projeto.funcoes_basicas.all %}
                        <li>
                            <a class="icon-link mb-1" href="{% url 'detalhes_funcao' projeto_id=funcao.id %}"
                                rel="noopener">
                                <svg class="bi" width="16" height="16">
                                    <use xlink:href="#arrow-right-circle" />
                                </svg>
                                {{funcao.nome}}
                            </a>
                        </li>
                        {% endfor%}

                        <div class="col-lg-6 col-xxl-4 my-3 ">
                            <div class="d-grid gap-2">
                                {% if tamanho_funcao > 5 %}
                                <button class="btn btn-outline-secondary" type="button"
                                    onclick="window.location.href='{% url 'funcoes' projeto_id=projeto.id %}'">Todas
                                    funções</button>
                                {% endif %}
                                <button class="btn btn-primary" type="button"
                                    onclick="window.location.href='{% url 'nova_funcao' projeto_id=projeto.id %}'">Nova
                                    funcionalidade</button>
                            </div>
                        </div>
                    </ul>
                </div>


                <!--Mais detalhes-->
                <div class="col-md-6">
                    <h2 class="text-body-emphasis">Mais Detalhes</h2>
                    <p>Read more detailed instructions and documentation on using or contributing to Bootstrap.</p>
                    <ul class="list-unstyled ps-0">
                        <li>
                            <p class="icon-link mb-1">
                                <svg class="bi" width="16" height="16">
                                    <use xlink:href="#arrow-right-circle" />
                                </svg>
                                Estado: {{ projeto.estado_projeto }}
                            </p>
                        </li>
                        <li>
                            <p class="icon-link mb-1">
                                <svg class="bi" width="16" height="16">
                                    <use xlink:href="#arrow-right-circle" />
                                </svg>
                                Prioridade: {{ projeto.prioridade}}
                            </p>
                        </li>
                        <li>
                            <p class="icon-link mb-1">
                                <svg class="bi" width="16" height="16">
                                    <use xlink:href="#arrow-right-circle" />
                                </svg>
                                Tempo Total do Projeto: {{ hora_total_gasta }}
                            </p>
                        </li>
                        <li>
                            <p class="icon-link mb-1">
                                <svg class="bi" width="16" height="16">
                                    <use xlink:href="#arrow-right-circle" />
                                </svg>
                                Email: {{ projeto.email_usuario }}
                            </p>
                        </li>
                        {% if exibir_botao %}
                        <div class="col-lg-6 col-xxl-4 my-3 ">
                            <div class="d-grid gap-2">
                                <button class="btn btn-primary" type="button"
                                    onclick="window.location.href='{% url 'adicionar_trabalho' projeto_id=projeto.id %}'">Adiciona
                                    o tempo</button>
                            </div>
                        </div> 
                        {% endif %}
                    </ul>
                </div>
            </div>
        </main>
    </div>
    </div>

    <div class="d-flex gap-2 justify-content-center py-5">
        <button class="btn btn-outline-secondary d-inline-flex align-items-center" type="button"
            onclick="window.location.href='{% url 'projetos' %}'">
            Voltar
            <svg class="bi ms-1" width="20" height="20">
                <use xlink:href="#arrow-right-short" />
            </svg>
        </button>
    </div>

{% endblock %}

project/templates/visualizar/todas_funcoes.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<div class="row g-5">
    <div class="col-md-6">
        <h2 class="text-body-emphasis">Funções Principais</h2>
        <p>Ready to beyond the starter template? Check out these open source projects that you can quickly
            duplicate to a new GitHub repository.</p>
        <ul class="list-unstyled ps-0">
            {% for funcao in projeto.funcoes_basicas.all %}
            <li>
                <a class="icon-link mb-1" href="{% url 'detalhes_funcao' projeto_id=funcao.id %}"
                    rel="noopener">
                    <svg class="bi" width="16" height="16">
                        <use xlink:href="#arrow-right-circle" />
                    </svg>
                    {{funcao.nome}}
                </a>
            </li>
            {% endfor%}
        </ul>
    </div>

{% endblock %}

project/templates/visualizar/todos_projetos.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
    }

    .bi {
        vertical-align: -.125em;
        fill: currentColor;
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
        z-index: 1500;
    }


    .center-text {
      position: absolute;
      top: 75%;
      left: 50%;
      transform: translate(-50%, -50%);
  }
</style>


<!-- ... Filtros ... 

    vou adicionar filtros aqui

-->

<div class="album py-5 bg-body-tertiary">
    <h1 class="text-center text-primary h1">Meus Projetos</h1>
        <div class="container">
    </div>
</div>


<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <!-- ... Filtros ... -->
        <form method="get" action="{% url 'todos_projetos' %}" class="mt-3">
            <div class="row g-3">
            <div class="col-md-4">
                <label for="id_categoria">Dificuldades dos Projetos:</label>
                <select id="id_categoria" name="dificuldade" class="form-select">
                    <option value="" {% if not categoria_selecionada %}selected{% endif %}>Todas as categorias</option>
                    <option value="simples" {% if categoria_selecionada == 'simples' %}selected{% endif %}>Simples</option>
                    <option value="intermediario" {% if categoria_selecionada == 'intermediario' %}selected{% endif %}>Intermediarior</option>
                    <option value="complexo" {% if categoria_selecionada == 'complexo' %}selected{% endif %}>Complexo</option>
                    <option value="falta de recursos" {% if categoria_selecionada == 'falta de recursos' %}selected{% endif %}>Falta de recursos</option>
                    <option value="prazos apertados" {% if categoria_selecionada == 'prazos apertados' %}selected{% endif %}>Prazos apertados</option>
                    <option value="falta de experiencia" {% if categoria_selecionada == 'falta de experiencia' %}selected{% endif %}>Falta de experiência</option>
                    <option value="complexidade do projeto" {% if categoria_selecionada == 'complexidade do projeto' %}selected{% endif %}>Saúde</option>
                    <option value="falta de comunicacao" {% if categoria_selecionada == 'falta de comunicacao' %}selected{% endif %}>Falta de comuinicação</option>
                    <option value="falta de suporte da equipe" {% if categoria_selecionada == 'falta de suporte da equipe' %}selected{% endif %}>Falta de suporte da equipa</option>
                    <option value="conflitos de interesse" {% if categoria_selecionada == 'conflitos de interesse' %}selected{% endif %}>Conflitos de interesses</option>
                    <option value="problema de integracao" {% if categoria_selecionada == 'problema de integracao' %}selected{% endif %}>Problemas de integração</option>
                    <option value="outros" {% if categoria_selecionada == 'outros' %}selected{% endif %}>Outros</option>
                </select>
            </div>

            <div class="col-md-4">
                <label for="id_prioridade">Prioridade:</label>
                <select id="id_prioridade" name="prioridade" class="form-select">
                    <option value="" {% if not prioridade_selecionada %}selected{% endif %}>Todas as prioridades</option>
                    <option value="baixa" {% if prioridade_selecionada == 'baixa' %}selected{% endif %}>Baixa</option>
                    <option value="media" {% if prioridade_selecionada == 'media' %}selected{% endif %}>Media</option>
                    <option value="alta" {% if prioridade_selecionada == 'alta' %}selected{% endif %}>Alta</option>
                </select>
            </div>

            <div class="col-md-4">
                <label for="id_status" class="mr-2 ml-4">Estado:</label>
                <select id="id_status" name="status" class="form-select">
                    <option value="" {% if not status_selecionado %}selected{% endif %}>Todos</option>
                    <option value="andamento" {% if status_selecionado == 'andamento' %}selected{% endif %}>Em andamentos</option>
                    <option value="pausado" {% if status_selecionado == 'pausado' %}selected{% endif %}>Pausados</option>
                    <option value="finalizado" {% if status_selecionado == 'finalizado' %}selected{% endif %}>Finalizados</option>
                </select>
            </div>

            <div><input type="submit" value="Filtrar"></div>
        </form>
    </div>
</div>


<!--Card que vai mostrar meus projetos-->

<div class="album py-5 bg-body-tertiary">
    <div class="container">


        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for projeto in projetos %}
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                        xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                        preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef"
                            dy=".3em">{{ projeto.nome }}</text>
                    </svg>
                    <div class="card-body">
                        <p class="card-text">{{ projeto.descricao }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary"
                                    onclick="window.location.href='{% url 'detalhes_projeto' projeto_id=projeto.id %}' ">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary"
                                    onclick="window.location.href='{% url 'update_projeto' projeto_id=projeto.id %}'">Edit</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary"
                                    onclick="window.location.href='{% url 'apagar_projeto' projeto_id=projeto.id %}'">Apagar</button>
                            </div>
                            <small class="text-body-secondary">{{ projeto.hours_minutes_ago }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="container py-2 text-center">
            <h2 class="fw-light center-text">Nenhum projeto encontrado.</h2>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
            {% endblock %}